export EDITOR="nvim"
export GOPATH="${HOME}/go"
export PATH="${HOME}/bin:${HOME}/.cargo/bin:${HOME}/.local/bin:${GOPATH}/bin:/usr/local/bin:/usr/bin:/bin"
export RUST_SRC_PATH="${HOME}/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"
export TERMINAL="alacritty"
# export TERMINAL="urxvt"
